micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:tc:mysql:8:///db
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: root
    password: ""
    schema-generate: CREATE_DROP
    dialect: MYSQL
